import { supabase } from "../supabase";
import { ANONYMIZED_PATIENT_MESSAGE } from "./patientService";

/**
 * Body composition measurements (InBody) of the patients the doctor follows
 * (migration 24). RLS: the doctor only (is_staff()). Every write is audited
 * by the database. BMI is computed by the database from weight and height.
 */

/** What the doctor records; every value but the date and weight is optional. */
export interface BodyMeasurementInput {
  measured_at: string;
  appointment_id: string | null;
  weight_kg: number;
  height_cm: number | null;
  body_fat_pct: number | null;
  body_fat_kg: number | null;
  skeletal_muscle_kg: number | null;
  lean_mass_kg: number | null;
  waist_hip_ratio: number | null;
  visceral_fat_level: number | null;
  bmr_kcal: number | null;
  balance_upper_lower: string | null;
  body_type: string | null;
  cid_type: string | null;
  note: string | null;
}

export interface BodyMeasurement extends BodyMeasurementInput {
  id: string;
  patient_id: string;
  /** Generated by the database; null without a height. */
  bmi: number | null;
  created_at: string;
}

const COLUMNS =
  "id, patient_id, measured_at, appointment_id, weight_kg, height_cm, bmi, body_fat_pct, body_fat_kg, skeletal_muscle_kg, lean_mass_kg, waist_hip_ratio, visceral_fat_level, bmr_kcal, balance_upper_lower, body_type, cid_type, note, created_at";

const NUMERIC_KEYS = [
  "weight_kg",
  "height_cm",
  "bmi",
  "body_fat_pct",
  "body_fat_kg",
  "skeletal_muscle_kg",
  "lean_mass_kg",
  "waist_hip_ratio",
  "visceral_fat_level",
  "bmr_kcal",
] as const;

/** PostgREST may send numeric columns as strings; the screen needs numbers. */
const toMeasurement = (row: Record<string, unknown>): BodyMeasurement => {
  const out = { ...row } as Record<string, unknown>;
  for (const key of NUMERIC_KEYS) {
    const value = row[key];
    out[key] = value === null || value === undefined ? null : Number(value);
  }
  return out as unknown as BodyMeasurement;
};

/** The writable columns only: never id, patient_id, author or bmi. */
const toPayload = (input: BodyMeasurementInput) => ({
  measured_at: input.measured_at,
  appointment_id: input.appointment_id,
  weight_kg: input.weight_kg,
  height_cm: input.height_cm,
  body_fat_pct: input.body_fat_pct,
  body_fat_kg: input.body_fat_kg,
  skeletal_muscle_kg: input.skeletal_muscle_kg,
  lean_mass_kg: input.lean_mass_kg,
  waist_hip_ratio: input.waist_hip_ratio,
  visceral_fat_level: input.visceral_fat_level,
  bmr_kcal: input.bmr_kcal,
  balance_upper_lower: input.balance_upper_lower,
  body_type: input.body_type,
  cid_type: input.cid_type,
  note: input.note,
});

const SAVE_FAILED_MESSAGE =
  "No se pudo guardar la medición. Revisa tu conexión e intenta de nuevo.";

/**
 * P0001 carries a Spanish reason from the database (anonymized record,
 * future date, another patient's appointment); 23514 is a range check.
 * Anything else stays generic: the raw message may echo data.
 */
const saveError = (error: { code?: string; message: string }, fallback: string) => {
  console.error("[bodyMeasurementService] write failed:", error.code);
  if (error.code === "P0001") return new Error(error.message);
  if (error.code === "23514") {
    return new Error("Algún valor está fuera de rango. Revisa la medición.");
  }
  return new Error(fallback);
};

/** Every measurement of a patient, oldest first. */
export const listBodyMeasurements = async (
  patientId: string,
): Promise<BodyMeasurement[]> => {
  const { data, error } = await supabase
    .from("body_measurements")
    .select(COLUMNS)
    .eq("patient_id", patientId)
    .order("measured_at", { ascending: true })
    .order("created_at", { ascending: true });

  if (error) {
    console.error("[bodyMeasurementService] list failed:", error.code);
    throw new Error("No se pudieron cargar las mediciones.");
  }
  return ((data ?? []) as Record<string, unknown>[]).map(toMeasurement);
};

export const createBodyMeasurement = async (
  patientId: string,
  input: BodyMeasurementInput,
): Promise<BodyMeasurement> => {
  const { data, error } = await supabase
    .from("body_measurements")
    .insert({ patient_id: patientId, ...toPayload(input) })
    .select(COLUMNS)
    .single();

  if (error) throw saveError(error, SAVE_FAILED_MESSAGE);
  return toMeasurement(data as Record<string, unknown>);
};

export const updateBodyMeasurement = async (
  id: string,
  input: BodyMeasurementInput,
): Promise<BodyMeasurement> => {
  const { data, error } = await supabase
    .from("body_measurements")
    .update(toPayload(input))
    .eq("id", id)
    .select(COLUMNS)
    .maybeSingle();

  if (error) throw saveError(error, SAVE_FAILED_MESSAGE);
  if (!data) throw new Error("Esta medición ya no existe. Recarga el expediente.");
  return toMeasurement(data as Record<string, unknown>);
};

export const deleteBodyMeasurement = async (id: string): Promise<void> => {
  const { data, error } = await supabase
    .from("body_measurements")
    .delete()
    .eq("id", id)
    .select("id");

  if (error) {
    throw saveError(error, "No se pudo borrar la medición. Intenta de nuevo.");
  }
  if (!data || data.length === 0) {
    throw new Error("Esta medición ya no existe. Recarga el expediente.");
  }
};

/** Whether the doctor follows this patient's weight (patients.weight_tracking). */
export const getWeightTracking = async (patientId: string): Promise<boolean> => {
  const { data, error } = await supabase
    .from("patients")
    .select("weight_tracking")
    .eq("id", patientId)
    .maybeSingle<{ weight_tracking: boolean | null }>();

  if (error) {
    console.error("[bodyMeasurementService] weight tracking read failed:", error.code);
    throw new Error("No se pudo saber si el paciente lleva control de peso.");
  }
  return data?.weight_tracking === true;
};

/**
 * Turns weight tracking on or off. Writes ONLY patients.weight_tracking; an
 * anonymized record is never changed (zero updated rows).
 */
export const setWeightTracking = async (
  patientId: string,
  on: boolean,
): Promise<void> => {
  const { data, error } = await supabase
    .from("patients")
    .update({ weight_tracking: on })
    .eq("id", patientId)
    .is("anonymized_at", null)
    .select("id");

  if (error) {
    console.error("[bodyMeasurementService] weight tracking write failed:", error.code);
    throw new Error("No se pudo cambiar el control de peso. Intenta de nuevo.");
  }
  if (!data || data.length === 0) throw new Error(ANONYMIZED_PATIENT_MESSAGE);
};
